import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
// import { Nunito as FontSans} from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import Wrapper from "./components/wrapper";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "h-svh bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
